ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_all" ON students FOR ALL USING (true);
CREATE POLICY "allow_all" ON sessions FOR ALL USING (true);
CREATE POLICY "allow_all" ON attendance FOR ALL USING (true);
CREATE POLICY "allow_all" ON fees FOR ALL USING (true);
CREATE POLICY "allow_all" ON tests FOR ALL USING (true);
CREATE POLICY "allow_all" ON notes FOR ALL USING (true);
